---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: koca
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
